package com.phyapp.web.modal;
// Generated Aug 27, 2016 8:17:55 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.LinkedList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * Questiontype generated by hbm2java
 */
@Entity
@Table(name = "questiontype", catalog = "physiologydb")
public class Questiontype implements java.io.Serializable {

	private Integer id;
	private Integer type;
	private String description;
	private List<Question> questions = new LinkedList<Question>();
	private List<Testhistory> testhistories = new LinkedList<Testhistory>();

	public Questiontype() {
	}

	public Questiontype(Integer type, String description, List<Question> questions, List<Testhistory> testhistories) {
		this.type = type;
		this.description = description;
		this.questions = questions;
		this.testhistories = testhistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questiontype")
	@OrderBy("id")
	public List<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(List<Question> questions) {
		this.questions = questions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "questiontype")
	@OrderBy("id")
	public List<Testhistory> getTesthistories() {
		return this.testhistories;
	}

	public void setTesthistories(List<Testhistory> testhistories) {
		this.testhistories = testhistories;
	}

}
