package com.phyapp.web.modal;
// Generated Aug 27, 2016 8:17:55 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TesttypeHasQuestion generated by hbm2java
 */
@Entity
@Table(name = "testtype_has_question", catalog = "physiologydb")
public class TesttypeHasQuestion implements java.io.Serializable {

	private Integer id;
	private Question question;
	private Testtype testtype;

	public TesttypeHasQuestion() {
	}

	public TesttypeHasQuestion(Integer id, Question question, Testtype testtype) {
		this.id = id;
		this.question = question;
		this.testtype = testtype;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id", nullable = false, insertable = false, updatable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TestType_id", nullable = false, insertable = false, updatable = false)
	public Testtype getTesttype() {
		return this.testtype;
	}

	public void setTesttype(Testtype testtype) {
		this.testtype = testtype;
	}

}
