package com.phyapp.web.modal;
// Generated Aug 27, 2016 8:17:55 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Testtype generated by hbm2java
 */
@Entity
@Table(name = "testtype", catalog = "physiologydb")
public class Testtype implements java.io.Serializable {

	private Integer id;
	private String testName;
	private String description;
	private Integer status;
	private Set<TesttypeHasQuestion> testtypeHasQuestions = new HashSet<TesttypeHasQuestion>(0);
	private Set<Testhistory> testhistories = new HashSet<Testhistory>(0);
	private Set<Testdetail> testdetails = new HashSet<Testdetail>(0);

	public Testtype() {
	}
	
	public Testtype(String testName) {
		this.testName = testName;
		this.description= "NA";
		this.status= 0;
	}

	public Testtype(String testName, String description, Integer status, Set<TesttypeHasQuestion> testtypeHasQuestions,
			Set<Testhistory> testhistories, Set<Testdetail> testdetails) {
		this.testName = testName;
		this.description = description;
		this.status = status;
		this.testtypeHasQuestions = testtypeHasQuestions;
		this.testhistories = testhistories;
		this.testdetails = testdetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "testName")
	public String getTestName() {
		return this.testName;
	}

	public void setTestName(String testName) {
		this.testName = testName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testtype")
	public Set<TesttypeHasQuestion> getTesttypeHasQuestions() {
		return this.testtypeHasQuestions;
	}

	public void setTesttypeHasQuestions(Set<TesttypeHasQuestion> testtypeHasQuestions) {
		this.testtypeHasQuestions = testtypeHasQuestions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testtype")
	public Set<Testhistory> getTesthistories() {
		return this.testhistories;
	}

	public void setTesthistories(Set<Testhistory> testhistories) {
		this.testhistories = testhistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testtype")
	public Set<Testdetail> getTestdetails() {
		return this.testdetails;
	}

	public void setTestdetails(Set<Testdetail> testdetails) {
		this.testdetails = testdetails;
	}

}
